### PR TITLE
Nav bar

### PR DESCRIPTION
**Pull request by keithrpotempa**
1. git fetch --all
2. git checkout nav-bar
3. Verify that the nav bar: 

- looks good
- logo looks good
- all links work
- hover changes colors on all links
- the active page link background is a different color

4. Gimme them thumbs up!

### CODE REVIEW

**Comment by ChaseSully222** [comment]
🥇 👍

**Comment by sophialawesome** [comment]
I recommend fixing the nav bar so the text doesn't overlap when the viewer changes the size of the page. 🐨

**Comment by keithrpotempa** [comment]
Putting this pull request on hold until I get the header to shrink properly.

**Comment by keithrpotempa** [comment]
I've made the requested changes. The nav bar now shrinks more elegantly till around 500px viewport width. The font is a little larger. 

Please confirm the nav bar functions as desired at your earliest convenience.

**Comment by sophialawesome** [comment]
👍 🐈

**Comment by ChaseSully222** [comment]
changes look great! 👍

**Comment by keithrpotempa** [comment]
At your earliest convenience, please pull down this branch and check it out. It has merged everything thus far, excluding the footer. 

1. git fetch --all
2. git checkout nav-bar
3. Verify that the nav bar looks good
4. Verify that there are no serious issues with the site 
5. Gimme them thumbs up!

**Comment by ChaseSully222** [comment]
👍

**Comment by sophialawesome** [comment]
👍

**Pull request merged**
