### PR TITLE
Index page

### PR DESCRIPTION
**Pull request by keithrpotempa**
1.  `git fetch --all`
2. `git checkout index-page`
3. Verify that the index.html page is complete and meets exercise prerequisites.

- Known collaborators with the artist.
- A portrait of the artist. This component should have a photo and name.
- List of known aliases.
- Country of residence.

4. Verify that Nav elements (Home, Career, Personal, News Feed) look fine, links are correct, 
5. Give me thumbs up and I'll merge.

### CODE REVIEW

**Comment by sophialawesome** [comment]
Collaborators: Isobel Waller-Bridge, Olivia Colman, Sian Clifford

**Comment by keithrpotempa** [comment]
Updated based on Sophia's recommendations. Added:

- Known Collaborators
- Known Aliases

Please follow the above steps and confirm.

**Comment by sophialawesome** [comment]
fantastic

**Comment by sophialawesome** [comment]
<insert thumbs up emoji here>

**Comment by sophialawesome** [comment]
[insert thumbs up emoji here]

**Comment by ChaseSully222** [comment]
Looks fire, full send.

**Pull request merged**
